import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Playfair_Display } from 'next/font/google'

const playfairDisplay = Playfair_Display({ subsets: ['vietnamese'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfairDisplay.className}>
        <main className=''>
          <Navbar/>
          {children}
        </main>
      </body>
    </html>
  )
}
